### ISSUE TITLE
[META] Create wireframes for new website

### ISSUE THREAD

**Issue by el22or** [drupalrs/website#1]
Create ideas as wireframes.

**Comment by cukovicmilossp** [comment]
[Wireframe](http://zhnre2.axshare.com)

**Comment by el22or** [comment]
@cukovicmilossp Jako mi se svidja ovo sto si do sad uradio, sjajno je!

Gledam malo region u dnu sajta sto prikazuje naredne dogadjaje. Trebace nam resenje kad u najavi imamo samo jedan dogadjaj. Ono sto bih jos predlozio, a vezano za listanje i drugog sadrzaja, jeste da tezimo da prikazujemo paran broj rezultata. Zbog prelamanja tokom prikaza na manjim ekranima.
Mada, mozda jos nije vreme da mislimo o tome? Kazem ovo u slucaju da se "zakacimo" za wireframe kao da je konacan dizajn, posto sam imao takva iskustva.

**Comment by cukovicmilossp** [comment]
@el22or 

Evo updejtovane verzije wireframe-a: http://zhnre2.axshare.com

Uvezao sam i linkove u menije, pa je prototip i funkcionalan.

- dodat je prikaz kada imamo jedan event u najavi (može da se vidi na stranici "sajtovi u drupalu")
- stavio sam kod listanja ljudi da ih ima šestoro - paran, kako si predložio
- nova stranica "jedan otvoren individualac"
- nova stranica "kompanije"
- nova stranica "jedna otvorena kompanija"
- nova stranica "događaji"
- nova stranica "jedan otvoren događaj"
- nova stranica "blog"
- nova stranica "jedan otvoren blog"
- nova stranica "ponuda poslova"
- nova stranica "jedan otvoren posao"
- nova stranica "ponuda usluga"
- nova stranica "jedna otvorena usluga"
- nova stranica "kontakt"

Da, po meni treba da se zakačimo za wireframe to što će i biti osnova layouta kada budem krenuo da radim dizajn. Znači treba da ga definišemo barem 95% što se tiče kostura sajta.

Ako imaš neki trello ili drugu todo listu, stavi da taj ko se prijavi na slack, welcome message da vidi  drupal.rs link i da mu damo do znanja da može da se prijavi na newsletter.

Podeli sa zajednicom novi wireframe, na slack kanal #sajt pa neka ostave svoje komentare - zapažanja, predloge za unapređenje. Kasnije ćemo rezimirati i odlučiti šta je ok da ide sada u novu verziju, a šta će eventualno kasnije.

**Comment by cukovicmilossp** [comment]
Link ka dizajnu: http://takealook.studiopresent.com/projects-design/drupalrs

**Comment by el22or** [comment]
This is done.
