### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by vmincev** [drupalrs/website#16]
Ne može se registrovati nalog ako je popunjeno polje "Kompanija", a ime kompanije nije prethodno dodato. Trebalo bi možda izbaciti ovo polje u procesu registracije.

Javlja se sledeća greška:
_There are no entities matching "Canic Interactive".
This entity (file: 230) cannot be referenced._

**Comment by vmincev** [comment]
Dodajem na isti issue - Ako ne odabereš državu, ime, prezime i grad nestanu. Ok grad, ali ime i prezime valjda imaš i dalje, zar ne?

**Comment by el22or** [comment]
Ovo sve treba izbaciti i registraciju ostaviti "Simple as possible". Popunjavanje account-a moze da se radi i kasnije. Jer ako korisnik nije ni dobio email, sva polja mora ponovo da popunjava.

**Comment by vmincev** [comment]
Slažem se.

**Comment by aleksandarborosgyevi** [comment]
Za adresu sam koristio address field i malo cudno radi, moras odabrati drzavu da bi video ostala polja. Ovo sam za sada resio da imamo default srbiju odabranu. 
Izbacio sam sva polja iz registracije i sve se moze kasnije popuniti. 
Kompanija prvo mora da se unese kako bi mogla da se izabere na listi, za sada je tako napravljeno da moze svaki registrovani korisnik da doda kompaniju a admin kada je stavi u publish onda ce biti vidljiva na listi na user edit stranici
