### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by cukovicmilossp** [drupalrs/website#2]
Link ka dizajnu: http://takealook.studiopresent.com/projects-design/drupalrs

**Comment by cukovicmilossp** [comment]
@el22or je rekao sugestio oko fontova za body i title, to ću uraditi iduće nedelje i prikazati ovde.

**Comment by cukovicmilossp** [comment]
@masterbuilder je dao sugestije za logo, uradićemo korekcije i takođe ovde postavljam

**Comment by el22or** [comment]
@cukovicmilossp Upravo sam shvatio zasto mi logo deluje "cudno". Siva boja koja predstavlja belu! Ta siva mi se tu uopste ne uklapa. Moja sugestija je da se koristi bela (prava bela, #FFFFFF). Znam da je to nemoguce sa sadasnjim oblikom, ali moze da se promeni oblik, doda outline i sa njim da pozadina bude neke druge boje kako bi se istakle i crvena i plava i bela.
