### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by rinasek** [drupalrs/website#20]
1. Nakone registracije nemoguce je ulogavati se. Prvo prijavi da je captcha blokiran zbog reuse-a, a posle da username ili password nisu dobri.

2. Kada se password reset zatrazi, user se uloguje normalno i sacuva se promenjeni password. Nakon logout-a user ne moze da se uloguje.  (GO TO 1)

**Comment by el22or** [comment]
@rinasek Je l' ovo moze da se zatvori?

**Comment by rinasek** [comment]
Da

_________________________________________________________________________________________
*Miljenko Vujaklija*
*CEO / Co-Founder*
Circle Web Foundry DOO
Pančevo, Serbia

mail: mvujaklija@circlewf.com
skype: miljenko.vujaklija
phone: +381 60 08 02 083 <+381%2060%2008%2002%20083>


Save the forests! Do not print this mail/any document, unless necessary

**Comment by el22or** [comment]
Fixed.
